### ISSUE TITLE
Updating the snitch list doesn't remove snitches that have been destroyed

### ISSUE THREAD

**Issue by awoo-civ** [MrLittleKitty/Snitch-Master#3]
Issue from Snitch Visualizer: https://github.com/waffle-stomper/Snitch-Visualizer/issues/1

Steps to reproduce:
1. Place down a snitch
2. Update the snitch list
3. Destroy the snitch
4. Update the snitch list

The snitch field should disappear but it stays there.

**Comment by MrLittleKitty** [comment]
Yeah I am definitely aware of this issue as it has basically been around since the invention of Snitch Visualizer. However, it is a slightly more complicated problem than it seems. 

The main reason I never patched it out of Snitch Visualizer is that there are times when you don't want snitches to be removed just because they no longer appear in your /jalist. Just because the snitch no longer appears in /jalist doesn't necessarily means its been removed. The player could have just been removed from the group that snitch was on or just lost permission to list snitches for that group. Sometimes it would be very useful to still have a list of snitches from a group you are no longer on.

BUT, now with the Snitch List structure, there are more possibilities to what could be done to fix this. One thing I considered at a point was to have a default Snitch List where snitches would be added if they disappeared from /jalist. Do you have any suggestions for a different fix or does that sound like a viable solution?

**Comment by awoo-civ** [comment]
Ah, I hadn't considered that. Yeah, creating a special snitch list sounds like a fine solution. I'd name it 'Destroyed' and color it red by default. However, I think that snitches removed by the user himself should just be removed - https://github.com/MrLittleKitty/Snitch-Master/issues/5.

**Comment by MrLittleKitty** [comment]
Completed as of https://github.com/MrLittleKitty/Snitch-Master/commit/6a7755173564c1fbd6721597066d93eea1a0dd23.

A long time coming...
